<?php

require_once( __DIR__ . '/../php-typography/class-php-typography.php' );

// don't break without translation function
if ( ! function_exists( '__' ) ) {
	function &__( $string, $domain = null ) { return $string; }
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-11-08 at 13:00:19.
 */
class PHP_Typography_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var PHP_Typography
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \PHP_Typography\PHP_Typography( false );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Return encoded HTML string (everything except <>"').
     *
     * @param string $html
     */
    protected function clean_html( $html ) {
    	return str_replace( array('&lt;', '&gt;'), array('<', '>'), htmlentities( $html, ENT_NOQUOTES, 'utf-8', false ) );
    }

    /**
     * @covers PHP_Typography::set_defaults
     * @todo   Implement testSet_defaults().
     */
    public function testSet_defaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_tags_to_ignore
     */
    public function testSet_tags_to_ignore()
    {
    	$always_ignore = array( 'iframe', 'textarea', 'button', 'select', 'optgroup', 'option', 'map',
    							'style', 'head', 'title', 'script', 'applet', 'object', 'param' );
    	$self_closing_tags = array('area', 'base', 'basefont', 'br', 'frame', 'hr', 'img', 'input', 'link', 'meta');

    	// default tags
		$this->object->set_tags_to_ignore( array( 'code', 'head', 'kbd', 'object', 'option', 'pre',	'samp',
												  'script',	'noscript',	'noembed', 'select', 'style', 'textarea',
												  'title',	'var', 'math' ) );
		$this->assertArraySubset( array( 'code', 'head', 'kbd', 'object', 'option',	'pre', 'samp',
										 'script', 'noscript', 'noembed', 'select', 'style', 'textarea',
 								 		 'title', 'var', 'math' ), $this->object->settings['ignoreTags'] );
		foreach ( $always_ignore as $tag ) {
			$this->assertContains( $tag, $this->object->settings['ignoreTags'] );
		}
		foreach ( $self_closing_tags as $tag ) {
			$this->assertNotContains( $tag, $this->object->settings['ignoreTags'] );
		}

		// auto-close tag and something else
		$this->object->set_tags_to_ignore( array( 'img', 'foo' ) );
 		$this->assertContains( 'foo', $this->object->settings['ignoreTags'] );
    	foreach ( $self_closing_tags as $tag ) {
			$this->assertNotContains( $tag, $this->object->settings['ignoreTags'] );
		}
		foreach ( $always_ignore as $tag ) {
			$this->assertContains( $tag, $this->object->settings['ignoreTags'] );
		}

    }

    /**
     * @covers PHP_Typography::set_classes_to_ignore
     */
    public function testSet_classes_to_ignore()
    {
		$typo = $this->object;

		$typo->set_classes_to_ignore( 'foo bar' );
		$this->assertContains( 'foo', $this->object->settings['ignoreClasses'] );
		$this->assertContains( 'bar', $this->object->settings['ignoreClasses'] );

		$html = '<p><span class="foo">Ignore this "quote",</span><span class="other"> but not "this" one.</span></p>
			     <p class="bar">"This" should also be ignored. <span>And "this".</span></p>
				 <p><span>"But" not this.</span></p>';
		$expected = '<p><span class="foo">Ignore this "quote",</span><span class="other"> but not &ldquo;this&rdquo; one.</span></p>
			     <p class="bar">"This" should also be ignored. <span>And "this".</span></p>
				 <p><span>&ldquo;But&rdquo; not this.</span></p>';
		$this->object->set_smart_quotes( true );
		$this->assertSame( $expected, $this->clean_html( $typo->process( $html ) ) );
    }

    /**
     * @covers PHP_Typography::set_ids_to_ignore
     * @todo   Implement testSet_ids_to_ignore().
     */
    public function testSet_ids_to_ignore()
    {
		$typo = $this->object;

		$typo->set_ids_to_ignore( 'foobar barfoo' );
		$this->assertContains( 'foobar', $this->object->settings['ignoreIDs'] );
		$this->assertContains( 'barfoo', $this->object->settings['ignoreIDs'] );

		$html = '<p><span id="foobar">Ignore this "quote",</span><span class="other"> but not "this" one.</span></p>
			     <p id="barfoo">"This" should also be ignored. <span>And "this".</span></p>
				 <p><span>"But" not this.</span></p>';
		$expected = '<p><span id="foobar">Ignore this "quote",</span><span class="other"> but not &ldquo;this&rdquo; one.</span></p>
			     <p id="barfoo">"This" should also be ignored. <span>And "this".</span></p>
				 <p><span>&ldquo;But&rdquo; not this.</span></p>';
		$this->object->set_smart_quotes( true );
		$this->assertSame( $expected, $this->clean_html( $typo->process( $html ) ) );
    }

    /**
     * @covers PHP_Typography::set_smart_quotes
     */
    public function testSet_smart_quotes()
    {
		$this->object->set_smart_quotes( true );
		$this->assertTrue( $this->object->settings['smartQuotes'] );

		$this->object->set_smart_quotes( false );
		$this->assertFalse( $this->object->settings['smartQuotes'] );
    }

    /**
     * @covers PHP_Typography::set_smart_quotes_primary
     * @todo   Implement testSet_smart_quotes_primary().
     */
    public function testSet_smart_quotes_primary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_smart_quotes_secondary
     * @todo   Implement testSet_smart_quotes_secondary().
     */
    public function testSet_smart_quotes_secondary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_smart_dashes
     */
    public function testSet_smart_dashes()
    {
		$this->object->set_smart_dashes( true );
		$this->assertTrue( $this->object->settings['smartDashes'] );

		$this->object->set_smart_dashes( false );
		$this->assertFalse( $this->object->settings['smartDashes'] );
    }

    /**
     * @covers PHP_Typography::set_smart_ellipses
     */
    public function testSet_smart_ellipses()
    {
		$this->object->set_smart_ellipses( true );
		$this->assertTrue( $this->object->settings['smartEllipses'] );

		$this->object->set_smart_ellipses( false );
		$this->assertFalse( $this->object->settings['smartEllipses'] );
    }

    /**
     * @covers PHP_Typography::set_smart_diacritics
     * @todo   Implement testSet_smart_diacritics().
     */
    public function testSet_smart_diacritics()
    {
		$this->object->set_smart_diacritics( true );
		$this->assertTrue( $this->object->settings['smartDiacritics'] );

		$this->object->set_smart_diacritics( false );
		$this->assertFalse( $this->object->settings['smartDiacritics'] );
    }

    /**
     * @covers PHP_Typography::set_diacritic_language
     */
    public function testSet_diacritic_language()
    {
		$this->object->set_diacritic_language( 'en-US' );
		$this->assertGreaterThan( 0, count( $this->object->settings['diacriticWords'] ) );

		$this->object->set_diacritic_language( 'foobar' );
		$this->assertFalse( isset( $this->object->settings['diacriticWords'] ) );

		$this->object->set_diacritic_language( 'de-DE' );
		$this->assertTrue( isset( $this->object->settings['diacriticWords'] ) );
		$this->assertGreaterThan( 0, count( $this->object->settings['diacriticWords'] ) );
    }

    /**
     * @covers PHP_Typography::set_diacritic_custom_replacements
     * @todo   Implement testSet_diacritic_custom_replacements().
     */
    public function testSet_diacritic_custom_replacements()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_smart_marks
     */
    public function testSet_smart_marks()
    {
		$this->object->set_smart_marks( true );
		$this->assertTrue( $this->object->settings['smartMarks'] );

		$this->object->set_smart_marks( false );
		$this->assertFalse( $this->object->settings['smartMarks'] );
    }

    /**
     * @covers PHP_Typography::set_smart_math
     */
    public function testSet_smart_math()
    {
		$this->object->set_smart_math( true );
		$this->assertTrue( $this->object->settings['smartMath'] );

		$this->object->set_smart_math( false );
		$this->assertFalse( $this->object->settings['smartMath'] );
    }

    /**
     * @covers PHP_Typography::set_smart_exponents
     */
    public function testSet_smart_exponents()
    {
		$this->object->set_smart_exponents( true );
		$this->assertTrue( $this->object->settings['smartExponents'] );

		$this->object->set_smart_exponents( false );
		$this->assertFalse( $this->object->settings['smartExponents'] );
    }

    /**
     * @covers PHP_Typography::set_smart_fractions
     */
    public function testSet_smart_fractions()
    {
		$this->object->set_smart_fractions( true );
		$this->assertTrue( $this->object->settings['smartFractions'] );

		$this->object->set_smart_fractions( false );
		$this->assertFalse( $this->object->settings['smartFractions'] );
    }

    /**
     * @covers PHP_Typography::set_smart_ordinal_suffix
     */
    public function testSet_smart_ordinal_suffix()
    {
		$this->object->set_smart_ordinal_suffix( true );
		$this->assertTrue( $this->object->settings['smartOrdinalSuffix'] );

		$this->object->set_smart_ordinal_suffix( false );
		$this->assertFalse( $this->object->settings['smartOrdinalSuffix'] );
    }

    /**
     * @covers PHP_Typography::set_single_character_word_spacing
     */
    public function testSet_single_character_word_spacing()
    {
		$this->object->set_single_character_word_spacing( true );
		$this->assertTrue( $this->object->settings['singleCharacterWordSpacing'] );

		$this->object->set_single_character_word_spacing( false );
		$this->assertFalse( $this->object->settings['singleCharacterWordSpacing'] );
    }

    /**
     * @covers PHP_Typography::set_fraction_spacing
     */
    public function testSet_fraction_spacing()
    {
		$this->object->set_fraction_spacing( true );
		$this->assertTrue( $this->object->settings['fractionSpacing'] );

		$this->object->set_fraction_spacing( false );
		$this->assertFalse( $this->object->settings['fractionSpacing'] );
    }

    /**
     * @covers PHP_Typography::set_unit_spacing
     */
    public function testSet_unit_spacing()
    {
		$this->object->set_unit_spacing( true );
		$this->assertTrue( $this->object->settings['unitSpacing'] );

		$this->object->set_unit_spacing( false );
		$this->assertFalse( $this->object->settings['unitSpacing'] );
    }

    /**
     * @covers PHP_Typography::set_units
     */
    public function testSet_units()
    {
    	$units_as_array = array( 'foo', 'bar', 'xx/yy');
    	$units_as_string = implode( ', ', $units_as_array );

		$this->object->set_units( $units_as_array );
		foreach( $units_as_array as $unit ) {
			$this->assertContains( $unit, $this->object->settings['units'] );
		}

		$this->object->set_units( array() );
		foreach( $units_as_array as $unit ) {
			$this->assertNotContains( $unit, $this->object->settings['units'] );
		}

		$this->object->set_units( $units_as_string );
		foreach( $units_as_array as $unit ) {
			$this->assertContains( $unit, $this->object->settings['units'] );
		}
    }

    /**
     * @covers PHP_Typography::set_dash_spacing
     */
    public function testSet_dash_spacing()
    {
		$this->object->set_dash_spacing( true );
		$this->assertTrue( $this->object->settings['dashSpacing'] );

		$this->object->set_dash_spacing( false );
		$this->assertFalse( $this->object->settings['dashSpacing'] );
    }

    /**
     * @covers PHP_Typography::set_space_collapse
     */
    public function testSet_space_collapse()
    {
		$this->object->set_space_collapse( true );
		$this->assertTrue( $this->object->settings['spaceCollapse'] );

		$this->object->set_space_collapse( false );
		$this->assertFalse( $this->object->settings['spaceCollapse'] );
    }

    /**
     * @covers PHP_Typography::set_dewidow
     */
    public function testSet_dewidow()
    {
		$this->object->set_dewidow( true );
		$this->assertTrue( $this->object->settings['dewidow'] );

		$this->object->set_dewidow( false );
		$this->assertFalse( $this->object->settings['dewidow'] );
    }

    /**
     * @covers PHP_Typography::set_max_dewidow_length
     */
    public function testSet_max_dewidow_length()
    {
		$this->object->set_max_dewidow_length( 10 );
		$this->assertSame( 10, $this->object->settings['dewidowMaxLength'] );

		$this->object->set_max_dewidow_length( 1 );
		$this->assertSame( 5, $this->object->settings['dewidowMaxLength'] );

		$this->object->set_max_dewidow_length( 2 );
		$this->assertSame( 2, $this->object->settings['dewidowMaxLength'] );
    }

    /**
     * @covers PHP_Typography::set_max_dewidow_pull
     */
    public function testSet_max_dewidow_pull()
    {
		$this->object->set_max_dewidow_pull( 10 );
		$this->assertSame( 10, $this->object->settings['dewidowMaxPull'] );

		$this->object->set_max_dewidow_pull( 1 );
		$this->assertSame( 5, $this->object->settings['dewidowMaxPull'] );

		$this->object->set_max_dewidow_pull( 2 );
		$this->assertSame( 2, $this->object->settings['dewidowMaxPull'] );
    }

    /**
     * @covers PHP_Typography::set_wrap_hard_hyphens
     */
    public function testSet_wrap_hard_hyphens()
    {
		$this->object->set_wrap_hard_hyphens( true );
		$this->assertTrue( $this->object->settings['hyphenHardWrap'] );

		$this->object->set_wrap_hard_hyphens( false );
		$this->assertFalse( $this->object->settings['hyphenHardWrap'] );
    }

    /**
     * @covers PHP_Typography::set_url_wrap
     */
    public function testSet_url_wrap()
    {
		$this->object->set_url_wrap( true );
		$this->assertTrue( $this->object->settings['urlWrap'] );

		$this->object->set_url_wrap( false );
		$this->assertFalse( $this->object->settings['urlWrap'] );
    }

    /**
     * @covers PHP_Typography::set_email_wrap
     */
    public function testSet_email_wrap()
    {
		$this->object->set_email_wrap( true );
		$this->assertTrue( $this->object->settings['emailWrap'] );

		$this->object->set_email_wrap( false );
		$this->assertFalse( $this->object->settings['emailWrap'] );
    }

    /**
     * @covers PHP_Typography::set_min_after_url_wrap
     */
    public function testSet_min_after_url_wrap()
    {
		$this->object->set_min_after_url_wrap( 10 );
		$this->assertSame( 10, $this->object->settings['urlMinAfterWrap'] );

		$this->object->set_min_after_url_wrap( 0 );
		$this->assertSame( 5, $this->object->settings['urlMinAfterWrap'] );

		$this->object->set_min_after_url_wrap( 1 );
		$this->assertSame( 1, $this->object->settings['urlMinAfterWrap'] );
    }

    /**
     * @covers PHP_Typography::set_style_ampersands
     */
    public function testSet_style_ampersands()
    {
		$this->object->set_style_ampersands( true );
		$this->assertTrue( $this->object->settings['styleAmpersands'] );

		$this->object->set_style_ampersands( false );
		$this->assertFalse( $this->object->settings['styleAmpersands'] );
    }

    /**
     * @covers PHP_Typography::set_style_caps
     */
    public function testSet_style_caps()
    {
		$this->object->set_style_caps( true );
		$this->assertTrue( $this->object->settings['styleCaps'] );

		$this->object->set_style_caps( false );
		$this->assertFalse( $this->object->settings['styleCaps'] );
    }

    /**
     * @covers PHP_Typography::set_style_initial_quotes
     */
    public function testSet_style_initial_quotes()
    {
		$this->object->set_style_initial_quotes( true );
		$this->assertTrue( $this->object->settings['styleInitialQuotes'] );

		$this->object->set_style_initial_quotes( false );
		$this->assertFalse( $this->object->settings['styleInitialQuotes'] );
    }

    /**
     * @covers PHP_Typography::set_style_numbers
     */
    public function testSet_style_numbers()
    {
		$this->object->set_style_numbers( true );
		$this->assertTrue( $this->object->settings['styleNumbers'] );

		$this->object->set_style_numbers( false );
		$this->assertFalse( $this->object->settings['styleNumbers'] );
    }

    /**
     * @covers PHP_Typography::set_initial_quote_tags
     */
    public function testSet_initial_quote_tags()
    {
       	$tags_as_array = array( 'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'div' );
    	$tags_as_string = implode( ', ', $tags_as_array );

		$this->object->set_initial_quote_tags( $tags_as_array );
		foreach( $tags_as_array as $tag ) {
			$this->assertArrayHasKey( $tag, $this->object->settings['initialQuoteTags'] );
		}

		$this->object->set_initial_quote_tags( array() );
		foreach( $tags_as_array as $tag ) {
			$this->assertArrayNotHasKey( $tag, $this->object->settings['initialQuoteTags'] );
		}

		$this->object->set_initial_quote_tags( $tags_as_string );
		foreach( $tags_as_array as $tag ) {
			$this->assertArrayHasKey( $tag, $this->object->settings['initialQuoteTags'] );
		}
    }

    /**
     * @covers PHP_Typography::set_hyphenation
     */
    public function testSet_hyphenation()
    {
		$this->object->set_hyphenation( true );
		$this->assertTrue( $this->object->settings['hyphenation'] );

		$this->object->set_hyphenation( false );
		$this->assertFalse( $this->object->settings['hyphenation'] );
    }

    /**
     * @covers PHP_Typography::set_hyphenation_language
     * @todo   Implement testSet_hyphenation_language().
     */
    public function testSet_hyphenation_language()
    {
		$this->object->set_hyphenation_language( 'en-US' );
		$this->assertGreaterThan( 0, count( $this->object->settings['hyphenationPattern'] ) );
		$this->assertGreaterThan( 0, count( $this->object->settings['hyphenationPatternMaxSegment'] ) );
		$this->assertGreaterThan( 0, count( $this->object->settings['hyphenationPatternExceptions'] ) );

		$this->object->set_hyphenation_language( 'foobar' );
		$this->assertFalse( isset( $this->object->settings['hyphenationPattern'] ) );
		$this->assertFalse( isset( $this->object->settings['hyphenationPatternMaxSegment'] ) );
		$this->assertFalse( isset( $this->object->settings['hyphenationPatternExceptions'] ) );

		$this->object->set_hyphenation_language( 'de' );
		$this->assertTrue( isset( $this->object->settings['hyphenationPattern'] ) );
		$this->assertGreaterThan( 0, count( $this->object->settings['hyphenationPattern'] ) );
		$this->assertGreaterThan( 0, count( $this->object->settings['hyphenationPatternMaxSegment'] ) );
		$this->assertEmpty( $this->object->settings['hyphenationPatternExceptions'] ); // no exceptions in the German pattern file
    }

    /**
     * @covers PHP_Typography::set_min_length_hyphenation
     * @todo   Implement testSet_min_length_hyphenation().
     */
    public function testSet_min_length_hyphenation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_min_before_hyphenation
     * @todo   Implement testSet_min_before_hyphenation().
     */
    public function testSet_min_before_hyphenation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_min_after_hyphenation
     * @todo   Implement testSet_min_after_hyphenation().
     */
    public function testSet_min_after_hyphenation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_hyphenate_headings
     * @todo   Implement testSet_hyphenate_headings().
     */
    public function testSet_hyphenate_headings()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_hyphenate_all_caps
     * @todo   Implement testSet_hyphenate_all_caps().
     */
    public function testSet_hyphenate_all_caps()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_hyphenate_title_case
     * @todo   Implement testSet_hyphenate_title_case().
     */
    public function testSet_hyphenate_title_case()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_hyphenation_exceptions
     * @todo   Implement testSet_hyphenation_exceptions().
     */
    public function testSet_hyphenation_exceptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_languages
     */
    public function testGet_languages()
    {
    	$expected = array( 'bg', 'ca', 'cs', 'cy', 'da', 'de', 'el-Mono', 'el-Poly', 'en-GB', 'en-US',
    					   'es', 'et', 'eu', 'fi', 'fr', 'ga', 'gl', 'grc', 'hr', 'hu', 'ia', 'id', 'is',
    					   'it', 'la', 'lt', 'mn-Cyrl', 'no', 'pl', 'pt', 'ro', 'ru', 'sa', 'sh-Cyrl', 'sh-Latn',
    					   'sk', 'sl', 'sr-Cyrl', 'sv', 'tr', 'uk', 'zh-Latn' );
    	$not_expected = array( 'klingon', 'de-DE' );

    	$actual = $this->object->get_languages();
		foreach( $expected as $lang_code ) {
			$this->assertArrayHasKey( $lang_code, $actual );
		}
		foreach( $not_expected as $lang_code ) {
			$this->assertArrayNotHasKey( $lang_code, $actual );
		}
    }

    /**
     * @covers PHP_Typography::get_diacritic_languages
     * @todo   Implement testGet_diacritic_languages().
     */
    public function testGet_diacritic_languages()
    {
       	$expected = array( 'de-DE', 'en-US' );
       	$not_expected = array( 'es', 'et', 'eu', 'fi', 'fr', 'ga', 'gl', 'grc', 'hr', 'hu', 'ia', 'id', 'is',
    					       'it', 'la', 'lt', 'mn-Cyrl', 'no', 'pl', 'pt', 'ro', 'ru', 'sa', 'sh-Cyrl', 'sh-Latn',
    					   	   'sk', 'sl', 'sr-Cyrl', 'sv', 'tr', 'uk', 'zh-Latn' );

       	$actual = $this->object->get_diacritic_languages();
		foreach( $expected as $lang_code ) {
			$this->assertArrayHasKey( $lang_code, $actual );
		}
		foreach( $not_expected as $lang_code ) {
			$this->assertArrayNotHasKey( $lang_code, $actual );
		}
    }

    /**
     * @covers PHP_Typography::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::array_intersection
     * @todo   Implement testArray_intersection().
     */
    public function testArray_intersection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::nodelist_to_array
     * @todo   Implement testNodelist_to_array().
     */
    public function testNodelist_to_array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_ancestors
     * @todo   Implement testGet_ancestors().
     */
    public function testGet_ancestors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::has_class
     * @todo   Implement testHas_class().
     */
    public function testHas_class()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::process_feed
     * @todo   Implement testProcess_feed().
     */
    public function testProcess_feed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_prev_chr
     * @todo   Implement testGet_prev_chr().
     */
    public function testGet_prev_chr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_previous_textnode
     * @todo   Implement testGet_previous_textnode().
     */
    public function testGet_previous_textnode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_last_textnode
     * @todo   Implement testGet_last_textnode().
     */
    public function testGet_last_textnode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_next_textnode
     * @todo   Implement testGet_next_textnode().
     */
    public function testGet_next_textnode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_first_textnode
     * @todo   Implement testGet_first_textnode().
     */
    public function testGet_first_textnode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_next_chr
     * @todo   Implement testGet_next_chr().
     */
    public function testGet_next_chr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_block_parent
     * @todo   Implement testGet_block_parent().
     */
    public function testGet_block_parent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::detect_encoding
     * @todo   Implement testDetect_encoding().
     */
    public function testDetect_encoding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::smart_quotes
     * @todo   Implement testSmart_quotes().
     */
    public function testSmart_quotes()
    {
		//$html = '<p><em>"I\'m pretty sure,"</em> she said, & "He said \'We are <em>family</em>\'".</p>';
		//$expected = '<p><em>&ldquo;';

    	$this->object->set_smart_quotes( true );

		$this->assertSame( "<span>&ldquo;Double&rdquo;, &lsquo;single&rsquo;</span>",
						   $this->clean_html( $this->object->process( '<span>"Double", \'single\'</span>' ) ) );
    }

    /**
     * @covers PHP_Typography::smart_dashes
     * @todo   Implement testSmart_dashes().
     */
    public function testSmart_dashes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::smart_ellipses
     * @todo   Implement testSmart_ellipses().
     */
    public function testSmart_ellipses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::smart_diacritics
     */
    public function testSmart_diacritics()
    {
		$this->object->set_smart_diacritics( true );
		$this->object->set_diacritic_language( 'en-US' );

		$this->assertSame( $this->clean_html('<p>crème brûlée</p>'),
						   $this->clean_html( $this->object->process('<p>creme brulee</p>') ) );
    }

    /**
     * @covers PHP_Typography::translate_words
     * @todo   Implement testTranslate_words().
     */
    public function testTranslate_words()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::smart_marks
     * @todo   Implement testSmart_marks().
     */
    public function testSmart_marks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::smart_math
     * @covers PHP_Typography::_smart_math_callback
     */
    public function testSmart_math()
    {
    	$typo = $this->object;

		$typo->set_smart_math( true );

		// standard equations
		$this->assertSame( 'xx 7&minus;3=4 xx', $this->clean_html( $typo->process('xx 7-3=4 xx') ) );
		$this->assertSame( 'xx 3&times;3=5&divide;2 xx', $this->clean_html( $typo->process('xx 3*3=5/2 xx') ) );

		// some changes should be reversed (not all)
		$this->assertSame( 'xx 0815-4711 xx', $typo->process( 'xx 0815-4711 xx' ) );
 		$this->assertSame( 'xx 1/2 xx', $typo->process( 'xx 1/2 xx') );
		$this->assertNotSame( 'xx 2001-13-12 xx', $typo->process( 'xx 2001-13-12 xx' ) ); // not a valid date
		$this->assertSame( 'xx 2001-12-13 xx', $typo->process('xx 2001-12-13 xx') );
		$this->assertNotSame( 'xx 2001-13-13 xx', $typo->process('xx 2001-13-13 xx') ); // not a valid date
		$this->assertSame( 'xx 13-12-2002 xx', $typo->process('xx 13-12-2002 xx') );
		$this->assertSame( 'xx 12-13-2002 xx', $typo->process('xx 12-13-2002 xx') );
		$this->assertNotSame( 'xx 13-13-2002 xx', $typo->process('xx 13-13-2002 xx') ); // not a valid date
		$this->assertSame( 'xx 2001-12 xx', $typo->process('xx 2001-12 xx') );
		$this->assertSame( 'xx 2001-13 xx', $typo->process('xx 2001-13 xx') ); // apparently a valid day count
		$this->assertSame( 'xx 2001-100 xx', $typo->process('xx 2001-100 xx') );
		$this->assertSame( 'xx 12/13/2010 xx', $typo->process('xx 12/13/2010 xx') );
		$this->assertSame( 'xx 13/12/2010 xx', $typo->process('xx 13/12/2010 xx') );
		$this->assertSame( 'xx 13&divide;13&divide;2010 xx', $this->clean_html( $typo->process('xx 13/13/2010 xx') ) ); // not a valid date
    }

    /**
     * @covers PHP_Typography::smart_exponents
     * @todo   Implement testSmart_exponents().
     */
    public function testSmart_exponents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::smart_fractions
     * @todo   Implement testSmart_fractions().
     */
    public function testSmart_fractions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::smart_ordinal_suffix
     * @todo   Implement testSmart_ordinal_suffix().
     */
    public function testSmart_ordinal_suffix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::single_character_word_spacing
     * @todo   Implement testSingle_character_word_spacing().
     */
    public function testSingle_character_word_spacing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::dash_spacing
     * @todo   Implement testDash_spacing().
     */
    public function testDash_spacing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::space_collapse
     * @todo   Implement testSpace_collapse().
     */
    public function testSpace_collapse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::unit_spacing
     * @todo   Implement testUnit_spacing().
     */
    public function testUnit_spacing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::wrap_hard_hyphens
     * @todo   Implement testWrap_hard_hyphens().
     */
    public function testWrap_hard_hyphens()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::dewidow
     * @todo   Implement testDewidow().
     */
    public function testDewidow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::_dewidow_callback
     * @todo   Implement test_dewidow_callback().
     */
    public function test_dewidow_callback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::wrap_urls
     * @todo   Implement testWrap_urls().
     */
    public function testWrap_urls()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::wrap_emails
     * @todo   Implement testWrap_emails().
     */
    public function testWrap_emails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::style_caps
     * @todo   Implement testStyle_caps().
     */
    public function testStyle_caps()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::set_inner_html
     * @todo   Implement testSet_inner_html().
     */
    public function testSet_inner_html()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::style_numbers
     * @todo   Implement testStyle_numbers().
     */
    public function testStyle_numbers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::style_ampersands
     * @todo   Implement testStyle_ampersands().
     */
    public function testStyle_ampersands()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::style_initial_quotes
     * @todo   Implement testStyle_initial_quotes().
     */
    public function testStyle_initial_quotes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::hyphenation_pattern_injection
     * @todo   Implement testHyphenation_pattern_injection().
     */
    public function testHyphenation_pattern_injection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::hyphenate
     * @todo   Implement testHyphenate().
     */
    public function testHyphenate()
    {
		$this->object->set_hyphenation( true );
		$this->object->set_hyphenation_language( 'en-US' );
		$this->object->set_min_length_hyphenation(2);
		$this->object->set_min_before_hyphenation(2);
		$this->object->set_min_after_hyphenation(2);
		$this->object->set_hyphenate_headings( true );
		$this->object->set_hyphenate_all_caps( true );
		$this->object->set_hyphenate_title_case( true ); // added in version 1.5
		$this->object->set_hyphenation_exceptions( array( 'KING-desk' ) );

 	/*	$this->assertSame( "This is a paragraph with no embedded hyphenation hints and no hyphen-related CSS applied. Corporate gibberish follows. Think visionary. If you generate proactively, you may have to e-enable interactively. We apply the proverb \"Grass doesn't grow on a racetrack\" not only to our re-purposing but our power to matrix. If all of this comes off as dumbfounding to you, that's because it is! Our feature set is unparalleled in the industry, but our reality-based systems and simple use is usually considered a remarkable achievement. The power to brand robustly leads to the aptitude to embrace seamlessly. What do we streamline? Anything and everything, regardless of reconditeness",
 						   $this->clean_html( $this->object->process("This is a paragraph with no embedded hyphenation hints and no hyphen-related CSS applied. Corporate gibberish follows. Think visionary. If you generate proactively, you may have to e-enable interactively. We apply the proverb \"Grass doesn't grow on a racetrack\" not only to our re-purposing but our power to matrix. If all of this comes off as dumbfounding to you, that's because it is! Our feature set is unparalleled in the industry, but our reality-based systems and simple use is usually considered a remarkable achievement. The power to brand robustly leads to the aptitude to embrace seamlessly. What do we streamline? Anything and everything, regardless of reconditeness") ) );
		*/

    	$this->assertSame( 'A few words to hy&shy;phen&shy;ate, like KING&shy;desk. Re&shy;ally, there should be more hy&shy;phen&shy;ation here!',
						   $this->clean_html( $this->object->process( 'A few words to hyphenate, like KINGdesk. Really, there should be more hyphenation here!' ) ) );
    }

    /**
     * @covers PHP_Typography::do_hyphenate
     * @todo   Implement testDo_hyphenate().
     */
    public function testDo_hyphenate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::uchr
     * @todo   Implement testUchr().
     */
    public function testUchr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::is_odd
     * @todo   Implement testIs_odd().
     */
    public function testIs_odd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::mb_str_split
     * @todo   Implement testMb_str_split().
     */
    public function testMb_str_split()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHP_Typography::get_settings_hash
     */
    public function testGet_settings_hash()
    {
    	$typo = $this->object;

    	$typo->set_smart_quotes(true);
    	$hash1 = $typo->get_settings_hash(10);
    	$this->assertEquals( 10, strlen( $hash1 ) );

  		$typo->set_smart_quotes(false);
  		$hash2 = $typo->get_settings_hash(10);
  		$this->assertEquals( 10, strlen( $hash2 ) );

  		$this->assertNotEquals( $hash1, $hash2 );
    }
}
