#!/bin/bash

# Define some variables.
COMMAND="vendor/bin/phpcs"
ANALYSIS_FILE="/tmp/analysis_result_phpcs"
# Remove old analysis results.
rm -f $ANALYSIS_FILE

# Save version information.
echo "php_code_sniffer" > "${SCRUTINIZER_VERSION_FILE:-/dev/null}"
$COMMAND --version >> "${SCRUTINIZER_VERSION_FILE:-/dev/null}"
VERSION="unknown"
if [ -f "$SCRUTINIZER_VERSION_FILE" ]; then
	VERSION=$(cat $SCRUTINIZER_VERSION_FILE);
fi

# Print version information.
echo "Running $COMMAND --report=checkstyle $* ($VERSION)" >&2

# Finally, run PHPCS.
$COMMAND -p src/ tests/ --ignore=tests/perf.php,tests/coverage --extensions=php --colors --report-checkstyle=/tmp/analysis_result_phpcs "$@" >&2 || true

# Print & remove results file.
#cat $ANALYSIS_FILE
#rm -f $ANALYSIS_FILE
